### ISSUE TITLE
注册里面不可以？

### ISSUE THREAD

**Issue by jsjjl** [lvpangpang/weinihaigou-better#1]
注册里面不可以？

**Comment by lvpangpang** [comment]
不好意思，这我忘记做了哈

**Comment by lvpangpang** [comment]
用户名 15757135989 密码 123456 你直接登录就行

**Comment by jsjjl** [comment]
打包出来后，获取不到json数据怎么处理啊？

**Comment by jsjjl** [comment]
有了，是我们公司禁止了一些网站的原因。axios 里面的前缀域名是我本地的也可以正常获取？是怎么实现的？

**Comment by jsjjl** [comment]
你们线上用的还是老的，为什么不直接上vue啊

**Comment by lvpangpang** [comment]
我开发环境用了proxy解决跨域，所有接口都是加了/api 然后在config里面的index.js里面配置了proxyTable: {
        '/api': {
            target: 'http://www.weinihaigou.com',
            changeOrigin: true,
            pathRewrite: {
              '^/api': ''
            }
        }
    },

**Comment by lvpangpang** [comment]
你说我们正式环境用的不是vue的单页面？

**Comment by jsjjl** [comment]
恩，vue做小项目有案例吗？学习一下

**Comment by lvpangpang** [comment]
有  你去我首页 有好几个。。。

**Comment by lvpangpang** [comment]
现在正式环境用的是多页面的，vuejs只是做了渲染和数据驱动

**Comment by jsjjl** [comment]
大哥你qq多少啊？交个朋友

**Comment by jsjjl** [comment]
加你qq了，proxy怎么弄的啊？

**Comment by lvpangpang** [comment]
'/api': {
target: 'http://www.weinihaigou.com',
changeOrigin: true,
pathRewrite: {
'^/api': ''
}
}
},

**Comment by jsjjl** [comment]
你们公司有用数据接口模拟工具吗？和后端人员定义好接口后自己模拟接口来同步开发吗？

**Comment by chentong106140** [comment]
你好，我使用npm run build 打包出来后无法加载api数据，也改了const pxy = '';
还是不行啊

**Comment by mingxuan0624** [comment]
那个账号登录点了没反应。。注册点了之后显示空白页面咋回事咧.输入账户,密码点击登陆没反应
