### ISSUE TITLE
关于图片加载

### ISSUE THREAD

**Issue by wangdabaoqq** [lvpangpang/weinihaigou-better#2]
你好,关于分类图片加载我有看到你引入了imgLazy.js这里有个疑问,图片不是可以通过绑定lazy来进行懒加载的吗？那引入的这个的js有什么区别吗？

**Comment by lvpangpang** [comment]
你好  imgLazy.js是我用原生js写的图片懒加载插件 你说的 lazy是vue里面的修饰符，可以直接懒加载？

**Comment by wangdabaoqq** [comment]
不是我的意思说,同样的不是有vue图片懒加载的组件吗？imgLazy.js和图片懒加载组件实现的效果是一样的还是？

**Comment by lvpangpang** [comment]
对。。本胖没用vue的图片懒加载

**Comment by wangdabaoqq** [comment]
恩谢谢您,了解了!
