### ISSUE TITLE
小哥，登录问题解决没

### ISSUE THREAD

**Issue by zhangwei1011** [lvpangpang/weinihaigou-better#3]
我也正在寻找登录问题解决办法

**Comment by lvpangpang** [comment]
什么  这个项目 登录是可以的呀

**Comment by zhangwei1011** [comment]
嗯嗯，我搞岔了

**Comment by x-canglong** [comment]
请问你登录是怎么解决的呢？我怎么还是登不上

**Comment by zhangwei1011** [comment]
哪里有问题
原始邮件
发件人:x-canglongnotifications@github.com
收件人:lvpangpang/weinihaigou-betterweinihaigou-better@noreply.github.com
抄送:zhangweizw2417@163.com; Authorauthor@noreply.github.com
发送时间:2018年7月12日(周四) 17:54
主题:Re: [lvpangpang/weinihaigou-better] 小哥，登录问题解决没 (#3)


请问你登录是怎么解决的呢？我怎么还是登不上
